obj-y += psci.o
obj-y += suspend.o
obj-y += cpu_depend.o
obj-y += wakeup_src.o

obj-$(CFG_SUN8IW12P1) += sun8iw12p1_mem/
obj-$(CFG_SUN8IW15P1) += sun8iw15p1_mem/
obj-$(CFG_SUN8IW16P1) += sun8iw16p1_mem/

