obj-$(CFG_AXP803_USED) += pmu_axp803.o
obj-$(CFG_AXP2202_USED) += pmu_axp2202.o
obj-$(CFG_AXP806_USED) += pmu_axp806.o
obj-$(CFG_AXP858_USED) += pmu_axp858.o

obj-$(CFG_SUN50IW10P1) += pmu-sun50iw10p1/
obj-$(CFG_SUN50IW12P1) += pmu-sun50iw12p1/

