#!/bin/sh

# Check for git and a git repo.
git_version() {
	if head=`git rev-parse --verify HEAD 2>/dev/null`; then
		# If we are at a tagged commit (like "v2.6.30-rc6"), we ignore
		# it, because this version is defined in the top level Makefile.

			# If we are past a tagged commit (like
			# "v2.6.30-rc5-302-g72357d5"), we pretty print it.
			if atag="`git describe 2>/dev/null`"; then
				echo -n "$atag"

			# If we don't have a tag at all we print -g{commitish}.
			else
			printf '%s' $head
			fi

			# Check for uncommitted changes
			if git diff-index --name-only HEAD | grep -qv "^scripts/"; then
				printf '%s' -dirty
			fi

	fi
	# All done with git
	return
}

git_version;
