#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=55
STOP=1
DEPEND=fstab
USE_PROCD=1
PROG=/usr/share/klippy-env/bin/python
USERDATA=/mnt/UDISK/
PRINTER_CONFIG_DIR=$USERDATA/printer_config
PRINTER_LOGS_DIR=$USERDATA/printer_logs
PRINTER_CUSTOM_CFG=/usr/share/klipper-brain/printer_config/config/printer-Ender3s1-401-changce.cfg
VIRTUAL_SD=/root/gcode_files
REAL_SD=$USERDATA/.crealityprint/upload
OOM_ADJ=-17
# /usr/share/klippy-env/bin/python /usr/share/klipper/klippy/klippy.py /usr/share/klipper-brain/printer_config/config/printer-Ender3v2-V4.2.2-V4.3.1.cfg -l /mnt/UDISK//printer_logs/klippy.log -a /tmp/klippy_uds &
start_service() {

    [ -d $PRINTER_CONFIG_DIR ] || mkdir -p $PRINTER_CONFIG_DIR
    [ -d $PRINTER_CONFIG_DIR ] && chmod o=rwx $PRINTER_CONFIG_DIR

    [ -d $PRINTER_LOGS_DIR ] || mkdir -p $PRINTER_LOGS_DIR
    [ -d $PRINTER_LOGS_DIR ] && chmod o=rwx $PRINTER_LOGS_DIR

    [ -L $VIRTUAL_SD ] || ln -s $REAL_SD $VIRTUAL_SD
    [ -d $REAL_SD ] && chmod o=rwx $REAL_SD

    procd_open_instance
    procd_set_param env HOME=/root
    procd_set_param oom_adj $OOM_ADJ
    procd_set_param command $PROG /usr/share/klipper/klippy/klippy.py $PRINTER_CUSTOM_CFG -l $PRINTER_LOGS_DIR/klippy.log -a /tmp/klippy_uds
    procd_close_instance
}

stop_service() {
	process=`ps | grep klpper_server_test | grep -v grep | awk '{print $1}'`
	[ -n "$process" ] && {
		for pid in $process
			do
				kill -9 $pid
			done
	}
}
