CFG_LOOP_TASK	= y
CFG_STANDBY	= y
CFG_SYSTEM_DEBUG = n
CFG_PIN_M_USED	= n

#rsb config
CFG_RSB_USED = y
CFG_HWCPUIDLE_USED = y
CFG_RSB_BYTE_OP = y
CFG_RSB_HALDWORD_OP = n
CFG_RSB_WORD_OP = n

#pmu config
CFG_PMU_USED = y
CFG_BMU_USED = n
CFG_PMU_AXP22X_USED = y
CFG_DVFS_USED = n
CFG_AVS_USED = y

CFG_SHELL_USED = n